repos:
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [--in-place, --remove-all-unused-imports]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
    args:
    - --in-place
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.14
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
  - id: mypy
    args:
    - --enable-error-code
    - ignore-without-code
    - --strict
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer
